### ISSUE TITLE
Update for Confluence 8.x support

### ISSUE THREAD

**Issue by boris-moduscreate** [codeclou/docker-atlassian-confluence-data-center#8]
Any chance you could update to support the 8.x version of Confluence?

I tried but couldn't get past:

```
./new-version.sh 7.5.0 8.1.1

°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸¸,ø¤º°`°º¤ø,¸

  Create new versions of Confluence Software Data Center docker-compose files
  version 2020-03-22 18:52

°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸¸,ø¤º°`°º¤ø,¸

>>
>> ACTION: new docker-compose files >  7.5.0 -> 8.1.1 
>>

>> trying to clone master branch
Cloning into 'docker-atlassian-confluence-data-center___master-branch'...
remote: Enumerating objects: 879, done.
remote: Total 879 (delta 0), reused 0 (delta 0), pack-reused 879
Receiving objects: 100% (879/879), 9.15 MiB | 75.57 MiB/s, done.
Resolving deltas: 100% (524/524), done.
   we are on master branch ...

>> trying to create new version 8.1.1 from old version 7.5.0.
   new version 8.1.1 does not yet exist. CONTINUE

   clone dir : versions/7.5.0 to versions/8.1.1
   replace   : 7.5.0 by 8.1.1 in docker-compose-four-nodes.yml
sed: -e expression #1, char 1: unknown command: `.'
```

**Comment by clouless** [comment]
Hi boris,
I am sorry we do not have the time to support this repo/solution anymore.
Due to switch to apple m2 chips we build our own docker images internally now and run our tests in GitHub Actions.
I will make the repo readonly now.

Just a last tip: Simply replace the docker versions in the docker-compose.yml files by hand, the script you are trying to use does that as well, but it needs write access to the repo and is only tested on macOS.

You will still be able to fork the current state of the repo and adapt it to your needs. I wish you success.

cheers,

Bernhard
